name: flutter_weather_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.2
  shared_preferences: ^2.2.2
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/evening_sunset.jpg
    - assets/images/morning_sunrise.jpg
    - assets/images/daytime_sunrise.jpg
    - assets/images/Background.jpg
